#Plugin: IPWL
#Author: Elb1to
#Version: 1.0-SNAPSHOT

#Custom IPWL plugin made for Mycraft Network (2019)

ip: "127.0.0.1"
permiso: "t6GrMqq3eBc6Z6Xr28hj1f9872.elb1to.gg"
mensaje: "&7(&4&l!&7) Deja de romper las pelotas y deja jugar a los demas."